### ISSUE TITLE
non-RPC operational models

### ISSUE THREAD

**Issue by networkop** [Juniper/yang#2]
Hi,
does JUNOS support any non-RPC based state models? e.g. IETF or OC?

**Comment by philshafer** [comment]
On Mar 30, 2017, at 4:13 PM, networkop <notifications@github.com> wrote:
> does JUNOS support any non-RPC based state models? e.g. IETF or OC?
> 

With the new YANG support, we allow importing any YANG model, along with translation scripts.  We’ve packages for openconfig, and should have them for ietf ones as well.  We can also to custom YANG models.

Thanks,
 Phil

**Comment by networkop** [comment]
Thanks, is there any documentation about this? and how do you distribute those packages?

**Comment by networkop** [comment]
Ok, i think i've found the openconfig guide https://www.juniper.net/documentation/en_US/junos/topics/task/installation/openconfig-installing.html

Is there any way to get those packages without a support account? I don't seem to have enough account privileges.

**Comment by philshafer** [comment]
The only channel I know is via your AM or SE.

Thanks,
 Phil

**Comment by networkop** [comment]
Ok. thanks.
